In [ ]:
!pip install -q scikit-learn joblib

In [ ]:
import pandas as pd
import numpy as np
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

print("Libraries loaded")

Libraries loaded

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'features.csv', 'molecules.csv', 'activity_data.csv', 'sample_data']

In [ ]:
!git clone https://github.com/21buddyboyal25-web/MoleculeRankAI.git

Cloning into 'MoleculeRankAI'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 33 (delta 11), reused 27 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (33/33), 1.19 MiB | 5.68 MiB/s, done.
Resolving deltas: 100% (11/11), done.

In [ ]:
import os

os.makedirs("/content/MoleculeRankAI/data", exist_ok=True)

print(os.listdir("/content/MoleculeRankAI"))

['requirements.txt', 'data', '.gitignore', '.git', 'dashboard', 'README.md', 'notebooks', 'extract_chembl.py', 'src', 'LICENSE']

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving features.csv to features (1).csv

In [ ]:
import shutil

shutil.move(
    "features.csv",
    "/content/MoleculeRankAI/data/features.csv"
)

'/content/MoleculeRankAI/data/features.csv'

In [ ]:
import os
print(os.listdir("/content/MoleculeRankAI/data"))

['features.csv', 'molecules.csv']

In [ ]:
features = pd.read_csv("/content/MoleculeRankAI/data/features.csv")

In [ ]:
import pandas as pd
import numpy as np
import os

data_path = "/content/MoleculeRankAI/data"

features = pd.read_csv(
    os.path.join(data_path, "features.csv")
)

print(features.shape)

features.head()

(45583, 6)

,canonical_smiles,MW,LogP,HBD,HBA,Rotatable
0,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl,341.754,2.11362,1,4,3
1,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1,332.319,1.33190,1,5,3
2,Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1,357.797,2.27274,2,4,3
3,Cc1ccc(C(=O)c2ccc(-n3ncc(=O)[nH]c3=O)cc2)cc1,307.309,1.46022,1,4,3
4,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(Cl)cc1,341.754,2.11362,1,4,3

In [ ]:
X = features[
    ["MW", "LogP", "HBD", "HBA", "Rotatable"]
]

y = features["MW"]

print(X.shape)
print(y.shape)

(45583, 5)
(45583,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(36466, 5)
(9117, 5)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train,
    y_train
)

print("Model trained successfully!")

Model trained successfully!

In [ ]:
import joblib
import os

os.makedirs("/content/MoleculeRankAI/models", exist_ok=True)

joblib.dump(
    model,
    "/content/MoleculeRankAI/models/rf_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!

In [ ]:
activity = pd.read_csv("activity_data.csv")

print(activity.shape)

activity.head()

(20926258, 5)

,chembl_id,canonical_smiles,standard_value,standard_units,standard_type
0,CHEMBL6329,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl,7.08,NaN,pH1/2
1,CHEMBL6329,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl,60.00,p.p.m.,MEC
2,CHEMBL6328,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1,7.08,NaN,pH1/2
3,CHEMBL6328,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1,125.00,p.p.m.,MEC
4,CHEMBL265667,Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1,30.00,p.p.m.,MEC

In [ ]:
activity["standard_value"] = pd.to_numeric(
    activity["standard_value"],
    errors="coerce"
)

activity = activity.dropna(subset=["standard_value"])

activity = activity.rename(
    columns={"standard_value": "IC50"}
)

print(activity.shape)

(20926258, 5)

In [ ]:
dataset = features.merge(
    activity,
    on="canonical_smiles",
    how="inner"
)

print(dataset.shape)

dataset.head()

(934254, 10)

,canonical_smiles,MW,LogP,HBD,HBA,Rotatable,chembl_id,IC50,standard_units,standard_type
0,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl,341.754,2.11362,1,4,3,CHEMBL6329,7.08,NaN,pH1/2
1,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl,341.754,2.11362,1,4,3,CHEMBL6329,60.00,p.p.m.,MEC
2,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1,332.319,1.33190,1,5,3,CHEMBL6328,7.08,NaN,pH1/2
3,Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1,332.319,1.33190,1,5,3,CHEMBL6328,125.00,p.p.m.,MEC
4,Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1,357.797,2.27274,2,4,3,CHEMBL265667,30.00,p.p.m.,MEC

In [ ]:
X = dataset[
    ["MW", "LogP", "HBD", "HBA", "Rotatable"]
]

y = dataset["IC50"]

print(X.shape)
print(y.shape)

(934254, 5)
(934254,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(747403, 5)
(186851, 5)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train,
    y_train
)

print("Model trained successfully!")

Model trained successfully!

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

predictions = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, predictions))
print("R²:", r2_score(y_test, predictions))

MAE: 4.545366334928668e+23
R²: -1.0646897333700821e+21

In [ ]:
import os
import joblib

os.makedirs("/content/MoleculeRankAI/models", exist_ok=True)

joblib.dump(
    model,
    "/content/MoleculeRankAI/models/rf_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!

In [ ]:
import os
import joblib

# Create the models folder if it doesn't exist
os.makedirs("/content/MoleculeRankAI/models", exist_ok=True)

# Save the trained model
joblib.dump(
    model,
    "/content/MoleculeRankAI/models/rf_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!

In [ ]:
from google.colab import files

files.download("/content/MoleculeRankAI/models/rf_model.pkl")