In [ ]:
import pandas as pd
import numpy as np

import joblib

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report
)

from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

In [ ]:
import os

os.listdir("/content")

['.config', 'sample_data']

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
import os
import numpy as np

print(os.getcwd())
print(os.path.abspath("fingerprints.npy"))
print(os.path.getsize("fingerprints.npy"))

with open("fingerprints.npy", "rb") as f:
    print(f.read(20))

/content
/content/fingerprints.npy
204800128
b"\x93NUMPY\x01\x00v\x00{'descr': "

In [ ]:
import numpy as np

fingerprints = np.load(
    "fingerprints.npy"
)

print(fingerprints.shape)

(100000, 2048)

In [ ]:
features = pd.read_csv("/content/features (1).csv")

activity = pd.read_csv("/content/activity.csv")

print(features.shape)
print(activity.shape)
print(fingerprints.shape)

(100000, 6)
(100000, 2)
(100000, 2048)

In [ ]:
import pandas as pd
import numpy as np

features = pd.read_csv("/content/features (1).csv")

activity = pd.read_csv("/content/activity.csv")

fingerprints = np.load("/content/fingerprints.npy")

print("Features:", features.shape)
print("Activity:", activity.shape)
print("Fingerprints:", fingerprints.shape)

Features: (100000, 6)
Activity: (100000, 2)
Fingerprints: (100000, 2048)

In [ ]:
activity.head()
activity.columns

Index(['canonical_smiles', 'chembl_id'], dtype='object')

In [ ]:
print(len(features))
print(len(activity))
print(len(fingerprints))

100000
100000
100000

In [ ]:
X = fingerprints

In [ ]:
activity.columns

Index(['canonical_smiles', 'chembl_id'], dtype='object')

In [ ]:
activity.head()

                                   canonical_smiles     chembl_id
0      Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl    CHEMBL6329
1   Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1    CHEMBL6328
2  Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1  CHEMBL265667
3      Cc1ccc(C(=O)c2ccc(-n3ncc(=O)[nH]c3=O)cc2)cc1    CHEMBL6362
4    Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(Cl)cc1  CHEMBL267864

In [ ]:
print(activity.columns)

Index(['canonical_smiles', 'chembl_id'], dtype='object')

In [ ]:
print(activity.columns.tolist())

['canonical_smiles', 'chembl_id']

In [ ]:
activity.head()

                                   canonical_smiles     chembl_id
0      Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl    CHEMBL6329
1   Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1    CHEMBL6328
2  Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1  CHEMBL265667
3      Cc1ccc(C(=O)c2ccc(-n3ncc(=O)[nH]c3=O)cc2)cc1    CHEMBL6362
4    Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(Cl)cc1  CHEMBL267864

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'clean_molecules.csv', 'features (1).csv', 'activity.csv', 'fingerprints.npy', 'sample_data']

In [ ]:
activity.head()
activity.shape

(100000, 2)

In [ ]:
features.head()
features.shape

(100000, 6)

In [ ]:
fingerprints.shape

(100000, 2048)

In [ ]:
features.isnull().sum()

canonical_smiles    0
MW                  0
LogP                0
HBD                 0
HBA                 0
Rotatable           0
dtype: int64

In [ ]:
features.dtypes

canonical_smiles     object
MW                  float64
LogP                float64
HBD                   int64
HBA                   int64
Rotatable             int64
dtype: object

In [ ]:
activity.dtypes

canonical_smiles    object
chembl_id           object
dtype: object

In [ ]:
# Verify that features and activity rows match by molecule
same_molecules = features["canonical_smiles"].equals(
    activity["canonical_smiles"]
)

print("Molecule order matches:", same_molecules)

print("Features rows:", len(features))
print("Activity rows:", len(activity))
print("Fingerprint rows:", len(fingerprints))

Molecule order matches: True
Features rows: 100000
Activity rows: 100000
Fingerprint rows: 100000

In [ ]:
# Prepare feature matrix
X = fingerprints

print("X shape:", X.shape)

X shape: (100000, 2048)

In [ ]:
# Show available activity columns and first rows
print(activity.columns.tolist())
print(activity.head())

['canonical_smiles', 'chembl_id']
                                   canonical_smiles     chembl_id
0      Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl    CHEMBL6329
1   Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1    CHEMBL6328
2  Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1  CHEMBL265667
3      Cc1ccc(C(=O)c2ccc(-n3ncc(=O)[nH]c3=O)cc2)cc1    CHEMBL6362
4    Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(Cl)cc1  CHEMBL267864

In [ ]:
# Check available CSV files and their columns
import os

for file in os.listdir("/content"):
    if file.endswith(".csv"):
        df = pd.read_csv(f"/content/{file}")
        print("\nFILE:", file)
        print("SHAPE:", df.shape)
        print("COLUMNS:", df.columns.tolist())

FILE: clean_molecules.csv
SHAPE: (60295, 3)
COLUMNS: ['canonical_smiles', 'chembl_id', 'clean_smiles']

FILE: features (1).csv
SHAPE: (100000, 6)
COLUMNS: ['canonical_smiles', 'MW', 'LogP', 'HBD', 'HBA', 'Rotatable']

FILE: activity.csv
SHAPE: (100000, 2)
COLUMNS: ['canonical_smiles', 'chembl_id']

In [ ]:
clean = pd.read_csv("/content/clean_molecules.csv")

print(clean.head())
print(clean["chembl_id"].nunique())
print(clean.shape)

                                   canonical_smiles     chembl_id  \
0      Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl    CHEMBL6329
1   Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1    CHEMBL6328
2  Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1  CHEMBL265667
3      Cc1ccc(C(=O)c2ccc(-n3ncc(=O)[nH]c3=O)cc2)cc1    CHEMBL6362
4    Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(Cl)cc1  CHEMBL267864

                                       clean_smiles
0      Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl
1   Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1
2  Cc1cc(-n2ncc(=O)[nH]c2=O)cc(C)c1C(O)c1ccc(Cl)cc1
3      Cc1ccc(C(=O)c2ccc(-n3ncc(=O)[nH]c3=O)cc2)cc1
4    Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(Cl)cc1
60295
(60295, 3)

In [ ]:
# Search all files for activity-related column names
import os

for file in os.listdir("/content"):
    if file.endswith((".csv", ".npy")):
        print(file)

clean_molecules.csv
features (1).csv
activity.csv
fingerprints.npy

In [ ]:
target_columns = [
    col for col in activity.columns
    if col not in ["canonical_smiles", "chembl_id"]
]

print("Target columns:", target_columns)

Target columns: []

In [ ]:
# Save the aligned training inputs
np.save("/content/X_fingerprints.npy", X)

features.to_csv("/content/features_ready.csv", index=False)

activity.to_csv("/content/molecules_ready.csv", index=False)

print("Saved.")

Saved.

In [ ]:
import sqlite3
import pandas as pd

db_path = r"C:\Users\21bud\MoleculeRankAI\data\chembl_37.db"

conn = sqlite3.connect(db_path)

tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

print(tables.head(20))

Empty DataFrame
Columns: [name]
Index: []

In [ ]:
import os

db_path = r"C:\Users\21bud\MoleculeRankAI\data\chembl_37.db"

print("Exists:", os.path.exists(db_path))

if os.path.exists(db_path):
    print("Size:", os.path.getsize(db_path), "bytes")

Exists: True
Size: 0 bytes

In [ ]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith(".db"):
            path = os.path.join(root, file)
            print(path, os.path.getsize(path))

/content/C:\Users\21bud\MoleculeRankAI\data\chembl_37.db 0
/content/.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db 12288
/content/.config/default_configs.db 12288

In [ ]:
import sqlite3

conn = sqlite3.connect(r"C:\Users\21bud\MoleculeRankAI\data\chembl_37.db")

print(conn.execute(
    "SELECT name FROM sqlite_master WHERE type='table' LIMIT 20"
).fetchall())

[]